version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  hub1:
    build:
      context: .
      dockerfile: Dockerfile.Hub
    ports:
      - "5987:5987"
    environment:
      ASPNETCORE_URLS: http://+:5987
      CONNECTIONSTRINGS__REDIS: redis
    depends_on: [ "redis" ]
  hub2:
    build:
      context: .
      dockerfile: Dockerfile.Hub
    ports:
      - "5988:5988"
    environment:
      ASPNETCORE_URLS: http://+:5988
      CONNECTIONSTRINGS__REDIS: redis
    depends_on: [ "redis" ]
  clientone:
    build:
      context: .
      dockerfile: Dockerfile.Client
    depends_on: ["hub1"]
    environment:
      CONNECTIONSTRINGS__HUB: http://hub1:5987/greetings
      GROUP__NAME: one
  clienttwo:
    build:
      context: .
      dockerfile: Dockerfile.Client
    depends_on: ["hub2"]
    environment:
      CONNECTIONSTRINGS__HUB: http://hub2:5988/greetings
      GROUP__NAME: two
  publisher:
    build:
      context: .
      dockerfile: Dockerfile.Publisher
    depends_on: ["hub2"]
    environment:
      CONNECTIONSTRINGS__HUB: http://hub2:5988/
