FROM mcr.microsoft.com/dotnet/sdk:6.0.100-alpine3.14 AS build
ARG Configuration=Release
WORKDIR /app

COPY . ./
RUN dotnet publish src/Hub -c $Configuration -o publish -r alpine-x64

FROM mcr.microsoft.com/dotnet/runtime-deps:6.0.0-alpine3.14
WORKDIR /app/publish
COPY --from=build /app/publish .
ENTRYPOINT ["./Hub"]
